### PR TITLE
Chore/imports

### PR DESCRIPTION
**Pull request by calumerskine**
## Description
Adds support for absolute imports using the following aliases:

- `~/` - denotes project root and can be used to target _any_ folders undernearth, eg: `~/components/Foo.tsx`, `~/types`, etc
- `~/server` - denotes the Next.js server API path, located at`./pages/api/*`, eg: `~/server/db.ts`

Further aliases can be created via `paths` in `tsconfig.json` for any absolute path:
`"~/dialogs/*": ["./components/dialog/*"]`

allows for
`import NewProjectDialog from '~/dialogs/NewProjectDialog'`

### CODE REVIEW

**Comment by calumerskine** [comment]
@matthewerskine I've opted to use the `server` alias to reference the server API routes instead of `api`. This is because the data layer on the client is currently found under `~/api`. Not sure if its worth renaming that data layer to reserve the `api` alias for server routes instead?

**Comment by matthewerskine** [comment]
@calumerskine Agreed, I found this naming convention of /api confusing at first. I don't know the best practice for separating backend & frontend data layers - I can imagine as this project grows we could use a monorepo approach (tools like Lerna).

Maybe we could rename `/api/*` to `/swr/*`?

**Comment by calumerskine** [comment]
@matthewerskine The `baseUrl: '.'` config gives us root lookups, meaning `import foo from 'swr'` is a valid local module. This overrides third-party imports of the same name, where in this case `useSwr` comes from `swr`. 

Have opted for `~/data` to refer to client-side swr location instead and allowed `~/api` to target server routes.

**Comment by matthewerskine** [comment]
Is this one ready to merge?

**Pull request merged**
